# Generated by Django 4.2.23 on 2025-06-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_id_doctor_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together={('patient_id', 'doctor_id')},
        ),
    ]
