# Generated by Django 4.2.23 on 2025-06-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_doctor_patientdoctormapping_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='mapping_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together={('patient', 'doctor')},
        ),
    ]
