# Generated by Django 4.2.23 on 2025-06-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_doctor_patientdoctormapping_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='patientdoctormapping',
            old_name='id',
            new_name='mapping_id',
        ),
    ]
